Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/08/2020
Var
// Seção de Declarações das variáveis 
contador: inteiro
nome:caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite seu nome: ")
leia (nome)

para contador de 1 ate 10 passo 1 faca
     escreval (contador," - ", nome)
fimpara

Fimalgoritmo