Algoritmo "Pares"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/08/2020
Var
// Seção de Declarações das variáveis 
Num:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   num <-2
      enquanto Num <=100 faca
       Escreva (num)
       num <- num + 2
       fimenquanto

Fimalgoritmo