Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
A: INTEIRO


Inicio
ESCREVA ("DIGITE SUA TEMPERATURA:")
LEIA (A)
ESCREVAL ()
   SE (A>=25)ENTAO
     ESCREVA("ESTÁ MUITO QUENTE!")
SENAO
   SE (A<=25)ENTAO
     ESCREVA("ESTÁ AGRADÁVEL!")
   FIMSE
   FIMSE


Fimalgoritmo